### ISSUE TITLE
Improvement - Add organisation search from value

### ISSUE THREAD

**Issue by AntoineBouquet** [bb-ffbb/bbffbb-scraper#2]
Need implementation to search organisation to use `clubSearchService: 'http://www.ffbb.com/ffbb-webservice/lookup-club?cd_lbclub='` FFBB endpoint

ping @bb-ffbb @defeo comme j'en aurais besoin pour mon projet, je m'occuperais de proposer une PR pour cette implémentation 😄

**Comment by defeo** [comment]
Veux-tu que je t'invite dans l'org bb-ffbb? L'idée de l'org c'était de mettre ensemble des dévs basketteurs frenchie pour développer des outils de support à la compét et au loisir. On n'est jamais allés très loin, très vite entraînés par autre chose, mais ton esprit me semble en ligne avec le notre, et je serai bien content de te donner la main sur ces dépôts.

**Comment by AntoineBouquet** [comment]
Pourquoi pas, ça pourrait être intéressant !
J'ai quelques idées de choses à faire, par exemple ajouter une autre fonctionnalité sur ce scrapper pour récupérer les catégories d'équipe d'un club. Pourquoi pas directement les créer sous ce groupe !

**Comment by AntoineBouquet** [comment]
@defeo désolé de te déranger. Serait-il possible de ta part de faire un `npm publish` de la version 0.0.3 (que je viens de bumpé) du projet lorsque tu auras le temps stp ? Je n'ai pas le droit de le faire.

**Comment by defeo** [comment]
C'est fait. Si tu me donnes ton compte npm, je t'ajoute en maintainer du projet.

**Comment by AntoineBouquet** [comment]
Merci !
Mon compte npm est antoinebouquet.
